FRANKS_PALADIN_HEALTH = 192
PALADIN_HEALTH_WITH_BLOODLINES = 180
PALADIN_HEALTH_WITHOUT_BLOODLINES = 160

PALADIN_HEALTH = 192
INITIAL_ENEMY_NUMBER = 150
MAXIMUM_ENEMY_NUMBER = 230
DEFAULT_PALADIN_ATTACK = 18
DEFAULT_PALADIN_NORMAL_ARMOR = 5
DEFAULT_PALADIN_PIERCE_ARMOR = 7
number_of_simulations_run = 200
Paladin_number = 40
